### ISSUE TITLE
https://github.com/LeeCampbell/RxCookbook/blob/master/Algorithms/GeneratingDeltas.md

### ISSUE THREAD

**Issue by headinthebox** [LeeCampbell/RxCookbook#14]
Why not use `Buffer(2,1)` instead of *ZipSkip*?

Also typo `yeild`.

**Comment by LeeCampbell** [comment]
LOL, cause I don't want to give all the tips and tricks away for free!! ;-)

I think this is code snippet is just showing is age. I would use the suggested `Buffer(2,1)` trick instead. I think it is more readable and less _faff_
